Checklist
VikaZinovieva/Sinatra pull request #3
Opened 2021-12-10 15:15 UTC by VikaZinovieva

2021-12-15 15:29 UTC, olichka12 requested changes

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 2.1 Verify POST/locations responce include all created data(name, description)
Verify POST/locations create location with data(name, description)

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 2.3 Verify POST/location length name 5 &  length description 1000 status code 201
Verify POST/location with length of  name 5 and length of description 1000 status code 201

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 2.6 Verify authorized user POST/locations response(name: empty, length less 2 and more 1000 characters) status code is 400
Verify POST/locations for authorized user with parameter name: empty, length less 2 and more 1000 characters doesn't create a location and returns status code 400

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 3.1 Verify PATCH/locations/name responce include new_name
Verify PATCH/locations/:name with new_name updates a location

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 3.5 Verify authorized user PATCH/locations/name responce length new_name(empty/less 5/more 100 status code) status code is 400
Verify PATCH/locations/:name for authorized user with length of new_name (empty/less 5/more 100) doesn't update a location and returns status code 400

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 4.1 Verify DELETE/locations/name request with name that will be deleted from db and replaced on new_name
Verify DELETE/locations/:name with parameter new_name of location for replace, deletes location with name and replaced on new_name location for employees which has deleted location

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 4. Verify non-authorized user DELETE/locations/name responce include new_name non-exist in db RETURNS status code 401
Add one more for case when name and new_name have the same values

2021-12-15 15:29 UTC, olichka12 commented on spec/checklists/locations
> + 2.15 Verify authorized user POST/location name & description  empty status code 401
Add case for Post only with name parameter and only with description parameter

2021-12-23 12:43 UTC, olichka12 requested changes

2021-12-23 12:43 UTC, olichka12 commented on lib/company.rb
> +require 'pry'
Please delete pry

2021-12-23 12:43 UTC, olichka12 commented on spec/locations/api_get_locations_spec.rb
> +  end
We have the same above in 6 row, this can be removed

2021-12-23 12:43 UTC, olichka12 commented on spec/locations/api_get_locations_spec.rb
> +      #empty: ''
Remove this comment

2021-12-23 12:43 UTC, olichka12 commented on spec/locations/api_post_locations_spec.rb
> +      # expect(list_of_names.include?(new_location['name'])).to be_truthy
Please remove pry here and in require
Also add checks to this test for name and description

2021-12-30 12:40 UTC, VikaZinovieva commented
Will be fixed in next PR

2021-12-30 12:41 UTC, merged