Custom rspec formatter,rake tasks
VikaZinovieva/Sinatra pull request #7
Opened 2022-02-01 15:27 UTC by VikaZinovieva

-made custom rspec formatter
-add rake tasks

2022-02-01 16:33 UTC, olichka12 requested changes

2022-02-01 16:33 UTC, olichka12 commented on tests/.rspec
> +--out reports/results/rspec<%= ENV["TEST_ENV_NUMBER"] %>.xml
Add one more line

2022-02-01 16:33 UTC, olichka12 commented on tests/Rakefile
> +RSpec::Core::RakeTask.new(:all_spec) do |t|
Can be in {}

2022-02-01 16:33 UTC, olichka12 commented on tests/Rakefile
> +task :parallel_rspec do |t, args|
In 11 row, you have the same rake task
Could you remove one of them?

2022-02-01 16:33 UTC, olichka12 commented on tests/support/rspec_formatter.rb
> +    " " * n
Edit to single quotes

2022-02-01 16:33 UTC, olichka12 commented on tests/reports/delete/api_delete_employees_spec.html
> +<!DOCTYPE html>
tests/reports can be added to gitignore

2022-02-02 10:21 UTC, closed without merging

2022-02-02 10:21 UTC, VikaZinovieva commented
Invalid project structure